export type EmailWorkflowKind = "user" | "manual" | "webhook" | "cron" | "broadcast";

export type EmailWorkflowStage =
  | "Lead capture"
  | "Conversion"
  | "Forms & waivers"
  | "Onboarding & readiness"
  | "Course operations"
  | "Saturday & conditions";

export interface EmailWorkflow {
  id: string;
  stage: EmailWorkflowStage;
  name: string;
  trigger: string;
  route: string;
  recipients: string;
  subject: string;
  kind: EmailWorkflowKind;
  statusEffect: string;
  ownerView: string;
  risk?: string;
}

export const EMAIL_WORKFLOWS: EmailWorkflow[] = [
  {
    id: "course-inquiry-confirmation",
    stage: "Lead capture",
    name: "Course inquiry confirmation",
    trigger: "Prospect submits public course inquiry.",
    route: "/api/course-inquiry",
    recipients: "Prospect",
    subject: "Course inquiry received — {course}",
    kind: "user",
    statusEffect: "Creates course_inquiries row.",
    ownerView: "/admin/inquiries",
  },
  {
    id: "course-inquiry-owner-notification",
    stage: "Lead capture",
    name: "Course inquiry owner notification",
    trigger: "Prospect submits public course inquiry.",
    route: "/api/course-inquiry",
    recipients: "Joshua",
    subject: "Course inquiry: {name} — {course}",
    kind: "user",
    statusEffect: "No extra status change beyond inquiry creation.",
    ownerView: "/admin/inquiries",
  },
  {
    id: "ai-inquiry-reply",
    stage: "Conversion",
    name: "AI-drafted inquiry reply",
    trigger: "Joshua drafts/sends a reply from inquiry pipeline.",
    route: "/api/admin/inquiries/reply",
    recipients: "Prospect",
    subject: "AI-generated, fallback Re: {course} inquiry",
    kind: "manual",
    statusEffect: "Marks inquiry replied.",
    ownerView: "/admin/inquiries",
    risk: "Uses hardcoded admin key today; should eventually use shared auth/secret handling.",
  },
  {
    id: "invoice-payment-link",
    stage: "Conversion",
    name: "Invoice / payment link",
    trigger: "Joshua creates invoice or payment link.",
    route: "/api/invoice",
    recipients: "Prospect/student when sendEmail is true",
    subject: "Invoice: {course} — ${amount}",
    kind: "manual",
    statusEffect: "Creates booking/invoice with invoice_sent or unpaid payment state.",
    ownerView: "/admin/invoices",
  },
  {
    id: "stripe-payment-confirmation",
    stage: "Conversion",
    name: "Stripe payment confirmation",
    trigger: "Stripe checkout session completed.",
    route: "/api/webhook/stripe",
    recipients: "Student",
    subject: "Payment confirmed — {courseName}",
    kind: "webhook",
    statusEffect: "Confirms booking, marks payment, links latest inquiry, issues portal magic link.",
    ownerView: "/admin/inquiries + /admin/courses",
  },
  {
    id: "stripe-payment-owner-notification",
    stage: "Conversion",
    name: "Stripe payment owner notification",
    trigger: "Stripe checkout session completed.",
    route: "/api/webhook/stripe",
    recipients: "Joshua",
    subject: "Payment: {student} — {courseName} — ${amount}",
    kind: "webhook",
    statusEffect: "Same Stripe confirmation transition.",
    ownerView: "/admin/inquiries + /admin/courses",
  },
  {
    id: "send-aida-forms",
    stage: "Forms & waivers",
    name: "Send AIDA forms",
    trigger: "Joshua sends forms manually.",
    route: "/api/send-forms",
    recipients: "Student",
    subject: "AIDA Course Forms — La Jolla Freedive Club",
    kind: "manual",
    statusEffect: "No visible status change from route.",
    ownerView: "/admin/send-forms",
  },
  {
    id: "aida-forms-student-confirmation",
    stage: "Forms & waivers",
    name: "AIDA forms submitted — student confirmation",
    trigger: "Student submits AIDA medical/liability forms.",
    route: "/api/aida-forms",
    recipients: "Student",
    subject: "AIDA Forms Submitted — {course}",
    kind: "user",
    statusEffect: "Stores AIDA form record.",
    ownerView: "/admin/students + /admin/courses",
  },
  {
    id: "aida-forms-owner-notification",
    stage: "Forms & waivers",
    name: "AIDA forms submitted — owner notification",
    trigger: "Student submits AIDA medical/liability forms.",
    route: "/api/aida-forms",
    recipients: "Joshua",
    subject: "AIDA Forms: {fullName} — {course}",
    kind: "user",
    statusEffect: "Stores AIDA form record; flags physician-required cases by email.",
    ownerView: "/admin/students + /admin/courses",
  },
  {
    id: "ljfc-waiver-owner-notification",
    stage: "Forms & waivers",
    name: "LJFC waiver signed — owner notification",
    trigger: "Student signs LJFC waiver.",
    route: "/api/waiver",
    recipients: "Joshua",
    subject: "Signed Waiver — {fullName}",
    kind: "user",
    statusEffect: "Generates PDF and stores/logs waiver status.",
    ownerView: "/admin/students + /admin/courses",
  },
  {
    id: "ljfc-waiver-student-copy",
    stage: "Forms & waivers",
    name: "LJFC waiver signed — student copy",
    trigger: "Student signs LJFC waiver.",
    route: "/api/waiver",
    recipients: "Student",
    subject: "Your LJFC Waiver — Signed Copy",
    kind: "user",
    statusEffect: "Sends signed PDF copy.",
    ownerView: "/admin/students + /admin/courses",
  },
  {
    id: "camp-waiver-owner-notification",
    stage: "Forms & waivers",
    name: "Camp waiver signed — owner notification",
    trigger: "Parent signs camp waiver.",
    route: "/api/camp-waiver",
    recipients: "Joshua",
    subject: "Camp Waiver Signed — {childName}",
    kind: "user",
    statusEffect: "Generates camp waiver PDF.",
    ownerView: "/admin/registrations",
  },
  {
    id: "camp-waiver-parent-copy",
    stage: "Forms & waivers",
    name: "Camp waiver signed — parent copy",
    trigger: "Parent signs camp waiver.",
    route: "/api/camp-waiver",
    recipients: "Parent/guardian",
    subject: "Camp Garibaldi Waiver — Signed Copy for {childName}",
    kind: "user",
    statusEffect: "Sends signed PDF copy.",
    ownerView: "/admin/registrations",
  },
  {
    id: "magic-link-login",
    stage: "Onboarding & readiness",
    name: "Magic-link login",
    trigger: "Student requests portal login link.",
    route: "/api/auth/magic-link",
    recipients: "Student",
    subject: "Your login link — La Jolla Freedive Club",
    kind: "user",
    statusEffect: "Updates student magic token.",
    ownerView: "/portal",
  },
  {
    id: "admin-onboarding-link",
    stage: "Onboarding & readiness",
    name: "Admin onboarding link",
    trigger: "Joshua sends onboarding link manually.",
    route: "/api/admin/send-links",
    recipients: "Student",
    subject: "Welcome — complete your pre-course onboarding",
    kind: "manual",
    statusEffect: "Creates/updates student and issues magic link.",
    ownerView: "/admin/send-links",
  },
  {
    id: "course-enrollment-invite",
    stage: "Onboarding & readiness",
    name: "Course enrollment invite",
    trigger: "Joshua enrolls student from course roster.",
    route: "/api/admin/courses action=enroll",
    recipients: "Student",
    subject: "You're enrolled — {courseName}",
    kind: "manual",
    statusEffect: "Creates student/booking; payment status pending.",
    ownerView: "/admin/courses",
  },
  {
    id: "resend-course-invite",
    stage: "Onboarding & readiness",
    name: "Resend course invite",
    trigger: "Joshua clicks resend invite from course roster.",
    route: "/api/admin/courses action=resend_invite",
    recipients: "Student",
    subject: "Reminder: {courseName} — get ready",
    kind: "manual",
    statusEffect: "No status change besides email.",
    ownerView: "/admin/courses",
  },
  {
    id: "course-readiness-reminder",
    stage: "Course operations",
    name: "Course readiness reminder",
    trigger: "Scheduled/manual reminder route before course.",
    route: "/api/course-reminder",
    recipients: "Student",
    subject: "Readiness-sensitive: ready vs missing items",
    kind: "cron",
    statusEffect: "Reminder only; does not mutate readiness.",
    ownerView: "/admin/courses",
  },
  {
    id: "course-briefing",
    stage: "Course operations",
    name: "Course briefing",
    trigger: "Scheduled/manual briefing route before course.",
    route: "/api/course-briefing",
    recipients: "Joshua",
    subject: "Course Briefing: {courseName} — {courseDates}",
    kind: "cron",
    statusEffect: "Briefing only.",
    ownerView: "/admin/courses",
  },
  {
    id: "inquiry-digest",
    stage: "Course operations",
    name: "Inquiry digest",
    trigger: "Scheduled/manual pipeline digest.",
    route: "/api/inquiry-digest",
    recipients: "Joshua",
    subject: "LJFC inquiries — {count} need attention / all clear",
    kind: "cron",
    statusEffect: "Attention summary only.",
    ownerView: "/admin/inquiries",
    risk: "One public fallback secret is hardcoded today; prefer CRON_SECRET only after confirming cron setup.",
  },
  {
    id: "course-roster-blast",
    stage: "Course operations",
    name: "Course roster blast",
    trigger: "Joshua sends message to event roster.",
    route: "/api/admin/courses action=blast_email",
    recipients: "Enrolled course participants",
    subject: "Joshua-supplied",
    kind: "manual",
    statusEffect: "Email only.",
    ownerView: "/admin/courses",
  },
  {
    id: "friday-reminder",
    stage: "Saturday & conditions",
    name: "Friday reminder",
    trigger: "Scheduled/manual reminder route.",
    route: "/api/friday-reminder",
    recipients: "Joshua",
    subject: "Friday reminder: Send the Saturday go/no-go",
    kind: "cron",
    statusEffect: "Reminder only.",
    ownerView: "/saturday",
  },
  {
    id: "saturday-go-nogo-broadcast",
    stage: "Saturday & conditions",
    name: "Saturday go/no-go broadcast",
    trigger: "Joshua sends Saturday blast.",
    route: "/api/saturday-blast",
    recipients: "Kit Saturday Crew segment/list",
    subject: "Generated from go/no-go type",
    kind: "broadcast",
    statusEffect: "Broadcast through Kit.",
    ownerView: "/saturday",
  },
  {
    id: "saturday-rsvp-student",
    stage: "Saturday & conditions",
    name: "Saturday RSVP confirmation",
    trigger: "User submits Saturday RSVP.",
    route: "/api/saturday-rsvp",
    recipients: "Participant",
    subject: "You're registered for Saturday — La Jolla Freedive Club",
    kind: "user",
    statusEffect: "Stores RSVP/member info.",
    ownerView: "/saturday",
  },
  {
    id: "saturday-rsvp-owner",
    stage: "Saturday & conditions",
    name: "Saturday RSVP owner notification",
    trigger: "User submits Saturday RSVP.",
    route: "/api/saturday-rsvp",
    recipients: "Joshua",
    subject: "Saturday RSVP: {name}",
    kind: "user",
    statusEffect: "Stores RSVP/member info.",
    ownerView: "/saturday",
  },
  {
    id: "daily-conditions-email",
    stage: "Saturday & conditions",
    name: "Daily conditions email",
    trigger: "Scheduled/manual daily-email route.",
    route: "/api/daily-email",
    recipients: "Joshua for preview/test; Kit list for broadcast",
    subject: "Conditions-dependent daily subject",
    kind: "broadcast",
    statusEffect: "Email/broadcast only.",
    ownerView: "/conditions + /saturday",
  },
];

export const EMAIL_WORKFLOW_STAGES: EmailWorkflowStage[] = [
  "Lead capture",
  "Conversion",
  "Forms & waivers",
  "Onboarding & readiness",
  "Course operations",
  "Saturday & conditions",
];

export function getEmailWorkflowsByStage(stage: EmailWorkflowStage) {
  return EMAIL_WORKFLOWS.filter((workflow) => workflow.stage === stage);
}
